title: Diana Lomelin # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS Analytics @ Georgia Tech. Sharpening my Data Science skills one project at a time.
  <br><br>
  I am fascinated with data and its endless possibilities and I feel true excitement for what humankind can accomplish through the power of data and technology.
  <br><br>
  <a href="https://www.linkedin.com/in/dianalomelinb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-dinky
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
